### ISSUE TITLE
Worklist issues/improvements

### ISSUE THREAD

**Issue by fedorov** [herrmannlab/slim#100]
- [ ] when I search for HTA12_9, which does exist, and I see it in the worklist, I get error popup "Study search failed"

<img width="376" alt="image" src="https://user-images.githubusercontent.com/313942/168832795-c9263c6b-be30-468f-8779-f8aa894e6e05.png">

<img width="387" alt="image" src="https://user-images.githubusercontent.com/313942/168832883-f2e0fce9-c402-409a-a340-c07e8181503c.png">

- [ ] #104

**Comment by hackermd** [comment]
I think that's an issue of the Google Healthcare API related to the implementation of QIDO-RS. Some of the attributes are not searchable, although they should be according to the standard. We have already reported the issue to Google.

**Comment by fedorov** [comment]
What about the second item in the issue?

**Comment by hackermd** [comment]
@fedorov I have converted the second item into a separate issue to facilitate tracking.

Will close this item, because there is currently nothing we can do about the first item. We have already reported the compliance issue of the Cloud Healthcare API to Google.
