### ISSUE TITLE
Would be useful to display ClinicalTrialProtocolID for Patient (Subject) in viewer

### ISSUE THREAD

**Issue by dclunie** [herrmannlab/slim#109]
Since this is populated with the collection name in IDC converted WSI, and is otherwise hard to figure out

**Comment by hackermd** [comment]
Yes, I have been thinking of exposing all clinical trial information at the patient and study level.

**Comment by dclunie** [comment]
I would follow the information model in the standard unless there is a good reason note to [http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_7.6.html](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_7.6.html)
