### ISSUE TITLE
Cannot zoom on HTAN image

### ISSUE THREAD

**Issue by Gibbsdavidl** [herrmannlab/slim#133]
I'm on Win10 and I've tried firefox and chrome.  Not able to zoom this image from HTAN.

https://viewer.imaging.datacommons.cancer.gov/slim/studies/2.25.162372274059988388010059723761949093273/series/1.3.6.1.4.1.5962.99.1.1997692069.2085034692.1655560133797.4.0?state=1.2.826.0.1.3680043.10.511.3.54275603117136698447923120717746116

**Comment by hackermd** [comment]
Thanks for reporting the issue @Gibbsdavidl. This slide appears to have only one resolution level so the behavior is expected.
