### ISSUE TITLE
How to convert WSI to DICOM format compatible with this viewer

### ISSUE THREAD

**Issue by vsaase** [herrmannlab/slim#86]
Hi,

I tried to convert a .ndpi WSI to dicom with [this library](https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter). The dicom files cannot be loaded with Slim, because they don't contain an OpticalPathSequence, i.e. error in this line: `image.OpticalPathSequence[0].OpticalPathIdentifier`

Then I tried [this library](https://github.com/smujiang/WSI2DICOM) for conversion. The viewer fails to load these dicom files with an error in `return image.ImageType[2] === imageFlavor`, i.e. there is no ImageType[2]

Which tools do you use for the conversions?

kind regards,
Victor

**Comment by fedorov** [comment]
@vsaase for the WSI data in Imaging Data Commons we have been using PixelMed tools (http://www.pixelmed.com/dicomtoolkit.html). But there is no documentation yet for the conversion process, it all has been done by @dclunie.

Thank you for sharing your experience with the tools you mentioned. We want to understand better their capabilities, but have not yet evaluated them well.

**Comment by dclunie** [comment]
@vsaase, the specific tool I use is documented at [https://www.dclunie.com/pixelmed/software/javadoc/com/pixelmed/convert/TIFFToDicom.html](https://www.dclunie.com/pixelmed/software/javadoc/com/pixelmed/convert/TIFFToDicom.html).

But it does not support NDPI files, only SVS (which is TIFF), generic TIFF and OME-TIFF.

NDPI file is the Hamamatsu NanoZoomer proprietary format, and though that scanner has been demonstrated to produce its own DICOM files in past Connectathons, I am not sure if that feature ever made it into the product (I will check).

@hackermd can probably tweak the Slim viewer to work without the missing information (even though it is required by the standard).

**Comment by hackermd** [comment]
@vsaase thanks for your interest in Slim and for reporting the problems your are facing.

Unfortunately, several of the existing converters are not fully conformant with the standard. As @dclunie pointed out the Optical Path Identifier and Image Type attributes are required by the standard. They are also critical for some of the core logic of the viewer and I am reluctant to try to a work around such flagrant violations of the standard.

I would suggest patching the image data sets before storing them in the archive. For example, if you know the type of the images, you can add this information yourself after conversion.

**Comment by fedorov** [comment]
@vsaase here's one tool that I used in the past that you can use to modify DICOM metadata: https://support.dcmtk.org/docs/dcmodify.html.

**Comment by j6u** [comment]
Hi Slim team, I am trying to use pixelmed for converting a svs to dicom image.

Do you mind sharing how I can do that?

So far I am doing:
`java -cp pixelmed.jar com.pixelmed.convert.TIFFToDicom slide.json tissue.svs tissue null 1.2.840.10008.5.1.4.1.1.77.1.6`
However I am getting nullexception.

Also I am curious if there are any correctly converted DICOMs that I can use for testing and reference. Cheers!

Much appreciated! @fedorov @hackermd @dclunie

**Comment by dclunie** [comment]
@j6u, you also need javax.json-1.0.4.jar (or equivalent) in the class path; this jar is in the lib/additional folder if you are using the dependencies that come with the release; its absence should give a ClassNotFoundException though, not a NullPointerException.

Followup with me directly at [dclunie@dclunie.com](mailto:dclunie@dclunie.com), since this has nothing to do with Slim.

PS. You should use "SM", not "null", for the Modality command line argument, but I doubt that triggers a null pointer exception; "null" is not a valid value for Modality in DICOM, and it is not converted to a null String.
