### ISSUE TITLE
Add support for google analytics

### ISSUE THREAD

**Issue by fedorov** [herrmannlab/slim#88]
Currently in IDC, we track the usage of our portal, OHIF Viewer, documentation portal, forum using Google Analytics. Usage tracking and understanding dynamics is important for the project. It would be great to have GA supported in Slim.

**Comment by fedorov** [comment]
As aside, I no longer have the permissions to assign labels to the issues I create. I was able to do that in the past.

**Comment by hackermd** [comment]
> Currently in IDC, we track the usage of our portal, OHIF Viewer, documentation portal, forum using Google Analytics. Usage tracking and understanding dynamics is important for the project. It would be great to have GA supported in Slim.

That seems to be highly specific to the IDC. Maybe something to consider to include in the IDC fork?

**Comment by hackermd** [comment]
> As aside, I no longer have the permissions to assign labels to the issues I create. I was able to do that in the past.

Can you try again?

**Comment by fedorov** [comment]
> Maybe something to consider to include in the IDC fork?

Agreed.
