### ISSUE TITLE
Slim 0.5.0 Service 'app' failed to build

### ISSUE THREAD

**Issue by DrexlerChao** [herrmannlab/slim#89]
Dear Sir,

We try to install the latest version 0.5.0.
But we failed to build service 'app' as follow,
![Screenshot from 2022-03-16 15-36-57](https://user-images.githubusercontent.com/27002631/158541188-d1617f2c-065b-499c-b44f-ce6e9d482e31.png)

Did we miss something that cause the error?

**Comment by hackermd** [comment]
@DrexlerChao could you please try whether #90 fixes the issue?

@cgorman we should probably also build the Docker container during the test workflow.

**Comment by DrexlerChao** [comment]
Hi @hackermd 

Thanks for your suggestion to build the Slim docker images successfully.

After _docker-compose up -d_ and connect to http://localhost:8008/
The Slim show the 403 Forbidden as follow,
![Screenshot from 2022-03-17 10-28-53](https://user-images.githubusercontent.com/27002631/158724812-a7f0c221-45cf-436e-8b29-39860cd347fb.png)

The Nginx seems "block" the connection to the Slim.
Any suggestion to fix the issue?

**Comment by DrexlerChao** [comment]
Hi @hackermd 

It works for us.
Thanks for your great help.
