### ISSUE TITLE
Slide content obscured by the overview panel

### ISSUE THREAD

**Issue by fedorov** [herrmannlab/slim#91]
I cam across an example where the field of view is pretty much the bounding box for the tissue section, and it is impossible to view the part of the specimen that is covered by the overview panel. The sample image to demonstrate this is not yet public in IDC, but when it is released, it will be here: studies/2.25.309938871000010255198523846507883889299/series/1.3.6.1.4.1.5962.99.1.1107168013.1232194229.1637489740557.2.0. Maybe it makes sense to make it possible to collapse the overview panel? 

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/313942/158725774-c23a6233-a372-4778-b295-be1ef5bd5dc5.png">

**Comment by hackermd** [comment]
Good point. We should add a button to toggle the overview.

**Comment by hackermd** [comment]
With [version 0.5.1](https://github.com/herrmannlab/slim/releases/tag/v0.5.1), the overview map can be collapsed

![Screen Shot 2022-03-24 at 10 35 13 PM](https://user-images.githubusercontent.com/6855297/160043472-5850192d-d259-44c3-9a78-6e7c3349ec21.png)
![Screen Shot 2022-03-24 at 10 35 21 PM](https://user-images.githubusercontent.com/6855297/160043484-87db065a-7b9b-4515-8d45-93b934e11fbf.png)
